name = "dev-auth"
main = "dist/index.mjs"
compatibility_date = "2026-08-24"

[[d1_databases]]
binding = "DB"
database_name = "dev-auth"
database_id = "3b301e9b-c16a-4b53-8866-6fbaf8fce320"

[[env.production.d1_databases]]
binding = "DB"
database_name = "prod-auth"
database_id = ""
